repos:
- hooks:
  - id: commitizen
    additional_dependencies: [cz-conventional-gitmoji]
  - id: commitizen-branch
    additional_dependencies: [cz-conventional-gitmoji]
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.6.0
