[project]
name = "dot-files"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "commitizen>=4.6.0",
    "cz-conventional-gitmoji>=0.7.0",
    "pre-commit>=4.2.0",
]
